### 对最大值和最小值进行高亮显示（内置函数）

In [1]:
# 导入基础计算库
import numpy as np
# 导入数据分析库
import pandas as pd
# 导入matplotlib包
import matplotlib as mpl

In [2]:
# 设置随机数种子
np.random.seed(0)
# 生成数据
df = pd.DataFrame(np.random.randn(10,4), columns=["A","B","C","D"])
df.style

In [3]:
# 最大值高亮显示
df.style.highlight_max(
    axis=1, # 行最大值
    props="color:white; font-weight:bold; background-color:darkblue;"
)

In [4]:
# 最大值高亮显示
df.style.highlight_max(
    axis=0, # 列最大值
    props="color:white; font-weight:bold; background-color:darkblue;"
)

In [5]:
# 最大值高亮显示
df.style.highlight_max(
    axis=None, # 整个dataframe最大值
    props="color:white; font-weight:bold; background-color:darkblue;"
)

In [6]:
# 最小值高亮显示
df.style.highlight_min(
    axis=1, # 行最小值
    props="color:white; font-weight:bold; background-color:darkblue;"
)

In [7]:
# 最小值高亮显示
df.style.highlight_min(
    axis=0, # 列最小值
    props="color:white; font-weight:bold; background-color:darkblue;"
)

In [8]:
# 最小值高亮显示
df.style.highlight_min(
    axis=None, # 整个dataframe最小值
    props="color:white; font-weight:bold; background-color:darkblue;"
)