### 对分位数进行高亮显示（内置函数）

In [1]:
# 导入基础计算库
import numpy as np
# 导入数据分析库
import pandas as pd
# 导入matplotlib包
import matplotlib as mpl

In [2]:
# 设置随机数种子
np.random.seed(0)
# 生成数据
df = pd.DataFrame(np.random.randn(10,4), columns=["A","B","C","D"])
df.style

In [3]:
# 将0.85到1的分位数高亮显示
df.style.highlight_quantile(
    q_left=0.85, axis=0, color="yellow" # 列
)

In [4]:
df.style.highlight_quantile(
    q_left=0.85, axis=1, color="yellow" # 行
)

In [5]:
df.style.highlight_quantile(
    q_left=0.85, axis=None, color="yellow" # 整个dataframe
)